---
systemLog:
  destination: file
  path: "var/log/mongodb/mongodb.log"
  logAppend: true
storage:
  dbPath: "data/db"
  journal:
    enabled: true
processManagement:
  fork: false
net:
  bindIp: 127.0.0.1
  port: 27017
setParameter:
  enableLocalhostAuthBypass: false
